#!/bin/bash
echo What is your start date? \(Please use the format YYYYMMDD\)
read start_date
echo What is your end date? \(Please use the format YYYYMMDD\)
read end_date
start_year=${start_date:0:4}
start_month=${start_date:4:2}
start_day=${start_date:6:2}
end_year=${end_date:0:4}
end_month=${end_date:4:2}
end_day=${end_date:6:2}
#echo $start_year-$start_month-$start_day
#echo $end_year-$end_month-$end_day
if [[ $start_month = 09 ]] || [[ $start_month = 04 ]] || [[ $start_month = 06 ]] || [[ $start_month = 11 ]]
then
	if [[ $start_day > 30 ]]
	then
		echo Please enter a valid date. Your selected month has no more than 30 days
		exit
	fi
elif [[ $start_month = 02 ]]
then
	if (( $start_year % 4 == 0 ))
	then 
		echo its a leap year
		exit
	fi
fi
if [[ $start_date = $end_date ]]
then
	sudo so-pcap-export "after $start_year-$start_month-${start_day}T00:00:00Z and before $start_year-$start_month-${start_day}T07:59:59Z" $start_date\_00:00-07:59
	sudo so-pcap-export "after $start_year-$start_month-${start_day}T08:00:00Z and before $start_year-$start_month-${start_day}T15:59:59Z" $start_date\_08:00-15:59
	sudo so-pcap-export "after $start_year-$start_month-${start_day}T16:00:00Z and before $start_year-$start_month-${start_day}T23:59:59Z" $start_date\_16:00-23:59
else
	for date in $(seq $start_date $end_date)
	do 
	sudo so-pcap-export "after ${date:0:4}-${date:4:2}-${date:6:2}T00:00:00Z and before ${date:0:4}-${date:4:2}-${date:6:2}T07:59:59Z" $date\_00:00-07:59
	sudo so-pcap-export "after ${date:0:4}-${date:4:2}-${date:6:2}T08:00:00Z and before ${date:0:4}-${date:4:2}-${date:6:2}T15:59:59Z" $date\_08:00-15:59
	sudo so-pcap-export "after ${date:0:4}-${date:4:2}-${date:6:2}T16:00:00Z and before ${date:0:4}-${date:4:2}-${date:6:2}T23:59:59Z" $date\_16:00-23:59
	done
fi
